name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker container
        run: |
          docker run -it --entrypoint /bin/bash bakcyl/paragon_back:${{ vars.DOCKER_IMAGE_VERSION }}

      - name: Create build directory
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest
