name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
      branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Branch name
        run: echo running on branch ${{ github.head_ref}} or ${{github.ref_name }} 
