name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker container
        run: |
          docker pull bakcyl/paragon_back
          docker run --name paragon_back -d bakcyl/paragon_back

      - name: Create build directory
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest
