name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker container
        id: run_docker
        run: |
          docker run --entrypoint appbuild.sh --name paragonTestBuild bakcyl/paragon_back:${{ vars.DOCKER_IMAGE_VERSION }}
        continue-on-error: true

      - name: Check GTest results
        run: |
          docker_exit_code=$(docker inspect -f '{{.State.ExitCode}}' paragonTestBuild)
          if [ $docker_exit_code -ne 0 ]; then
            echo "GTest failed! Docker container exited with code $docker_exit_code."
            exit 1
          fi
