name: C/C++ CI

on:
  push:
    branches:
      - main
      - 46-branch-not-set-in-c-cppyml
  pull_request:
      branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine Branch
        id: determine_branch
        run: echo "::set-output name=branch::${{ github.head_ref || vars.BRANCH }}"

      - name: Run Docker container
        run: |
          docker run --entrypoint appbuild.sh -e "REPO=${{ vars.REPO }}" -e "BRANCH=${{ steps.determine_branch.outputs.branch }}" --name paragonTestBuild bakcyl/paragon_back:${{ vars.DOCKER_IMAGE_VERSION }}
        continue-on-error: true

      - name: Check build results
        run: |
          exit $(docker logs paragonTestBuild 2>&1 | grep -iE "Error" | wc -l)

      - name: Check GTest results
        run: |
          exit $(docker logs paragonTestBuild 2>&1 | grep Failed | grep "Test #" | wc -l)
