name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev

      - name: Install gtest
        run: |
          sudo apt-get install -y libgtest-dev
          sudo apt-get install -y cmake
          cd /usr/src/gtest
          sudo cmake CMakeLists.txt
          sudo make
          sudo make install
          sudo mkdir -p /usr/lib/gtest
          sudo cp /usr/src/gtest/lib/*.a /usr/lib/gtest/
          sudo ldconfig  # Ensure dynamic linker knows about the library
          sudo make install  # Add this line to install the library
          sudo ln -s /usr/lib/gtest/libgtest.a /usr/lib/gtest/gtest_main.a  # Fix for gtest_main


      - name: Build and Install oat++
        run: |
          git clone --branch 1.3.0 --depth 1 https://github.com/oatpp/oatpp.git
          cd oatpp
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ../..

      - name: Build and Install oat++-swagger
        run: |
          git clone --branch 1.3.0 --depth 1 https://github.com/oatpp/oatpp-swagger.git
          cd oatpp-swagger
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          cd ../..

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Create build directory
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest
