name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: your-docker-image-name:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create build directory
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: |
          cd build
          ctest
