name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up CMake
        run: sudo apt-get install -y cmake

      - name: Create build directory
        run: cmake -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build

      - name: Run additional checks
        run: |
          cd build
          make check
          make distcheck
