name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: actions/setup-docker@v2

      - name: Build Docker image
        run: |
          docker build -t my-build-image \
            --build-arg OATPP_VERSION=1.3.0 \
            --build-arg OATPP_SWAGGER_VERSION=1.3.0 \
            - < Dockerfile

      - name: Run tests in Docker
        run: |
          docker run my-build-image
