name: C/C++ CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Run Docker container
        run: |
          docker run --entrypoint appbuild.sh -e "REPO=https://github.com/BakcylProgramowania/paragon_back.git" -e "BRANCH=${{ env.BRANCH_NAME }}" --name paragonTestBuild bakcyl/paragon_back:${{ vars.DOCKER_IMAGE_VERSION }}
        continue-on-error: true

      - name: Check build results
        run: |
          exit $(docker logs paragonTestBuild 2>&1 | grep -iE "Error" | wc -l)

      - name: Check GTest results
        run: |
          exit $(docker logs paragonTestBuild 2>&1 | grep Failed | grep "Test #" | wc -l)
