name: C/C++ CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Docker container
        run: |
          docker run --entrypoint appbuild.sh -e "REPO=${{ github.repository }}" -e "BRANCH=${{ github.ref_name }}" --name paragonTestBuild bakcyl/paragon_back:${{ env.DOCKER_IMAGE_VERSION }}
        continue-on-error: true

      - name: Check build results
        run: |
          exit $(docker logs paragonTestBuild 2>&1 | grep -iE "Error" | wc -l)

      - name: Check GTest results
        run: |
          exit $(docker logs paragonTestBuild 2>&1 | grep Failed | grep "Test #" | wc -l)
