name: Deploy staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: staging
    steps:
    - uses: actions/checkout@v2
    - name: stop existing container
      run: docker container stop ${{ vars.CONTAINER_NAME }}
    - name: remove container
      run: docker container rm ${{ vars.CONTAINER_NAME }}
    - name: run new container
      run: docker run --detach -e "REPO=${{ vars.REPO }}" -e "BRANCH=${{ vars.BRANCH }}" --hostname ${{ vars.DOMAIN }} --publish ${{ vars.API_PORT }}:8000 --name ${{ vars.CONTAINER_NAME }} --restart always bakcyl/paragon_back:${{ vars.DOCKER_IMAGE_VERSION }}
