name: Deploy prod

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: prod
    steps:
    - uses: actions/checkout@v2
    - name: stop existing container
      run: docker container stop ${{ vars.CONTAINER_NAME }}
    - name: remove container
      run: docker container rm ${{ vars.CONTAINER_NAME }}
    - name: run new container
      run: docker run --detach --hostname ${{ vars.DOMAIN }} --publish ${{ vars.API_PORT }}:8000 --name ${{ vars.CONTAINER_NAME }} --restart always bakcyl/paragon_back:${{ vars.DOCKER_IMAGE_VERSION }}
