name: Deploy staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    environment: staging
    steps:
    - uses: actions/checkout@v2
    - name: stop existing container
      run: docker container stop ${{ env.CONTAINER_NAME }}
    - name: remove container
      run: docker container rm ${{ env.CONTAINER_NAME }}
    - name: run new container
      run: docker run --detach --hostname ${{ env.DOMAIN }} --publish ${{ env.API_PORT }}:8000 --name ${{ env.CONTAINER_NAME }} --restart always bakcyl/paragon_back:${{ env.DOCKER_IMAGE_VERSION }}
