name: Deploy staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: stop existing container
      run: docker container stop paragon-staging
    - name: remove container
      run: docker container rm paragon-staging
    - name: run new container
      run: docker run --detach --hostname paragon-staging.wroc.ovh --publish 54110:8000 --name paragon-staging --restart always paragon_back:1.1.0
